// flow-typed signature: a7bb495162763d27932a47fa8d9c8bbf
// flow-typed version: <<STUB>>/react-native-version_v^2.4.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-version'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-version' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-version/cli' {
  declare module.exports: any;
}

declare module 'react-native-version/test/amend' {
  declare module.exports: any;
}

declare module 'react-native-version/test/amend.skipTag' {
  declare module.exports: any;
}

declare module 'react-native-version/test/default' {
  declare module.exports: any;
}

declare module 'react-native-version/test/default.skipTag' {
  declare module.exports: any;
}

declare module 'react-native-version/test/fixtures/index' {
  declare module.exports: any;
}

declare module 'react-native-version/test/helpers/apiMacro' {
  declare module.exports: any;
}

declare module 'react-native-version/test/helpers/beforeEach' {
  declare module.exports: any;
}

declare module 'react-native-version/test/helpers/cliMacro' {
  declare module.exports: any;
}

declare module 'react-native-version/test/helpers/execAsync' {
  declare module.exports: any;
}

declare module 'react-native-version/test/helpers/getCurrCommitHash' {
  declare module.exports: any;
}

declare module 'react-native-version/test/helpers/getCurrTagHash' {
  declare module.exports: any;
}

declare module 'react-native-version/test/helpers/getCurrTree' {
  declare module.exports: any;
}

declare module 'react-native-version/test/helpers/getCurrVersion' {
  declare module.exports: any;
}

declare module 'react-native-version/test/helpers/gitPathnames' {
  declare module.exports: any;
}

declare module 'react-native-version/test/helpers/npmScriptsMacro' {
  declare module.exports: any;
}

declare module 'react-native-version/test/helpers/tempInitAndVersion' {
  declare module.exports: any;
}

declare module 'react-native-version/test/incrementBuild' {
  declare module.exports: any;
}

declare module 'react-native-version/test/neverAmend' {
  declare module.exports: any;
}

declare module 'react-native-version/test/resetBuild' {
  declare module.exports: any;
}

declare module 'react-native-version/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-version/cli.js' {
  declare module.exports: $Exports<'react-native-version/cli'>;
}
declare module 'react-native-version/index' {
  declare module.exports: $Exports<'react-native-version'>;
}
declare module 'react-native-version/index.js' {
  declare module.exports: $Exports<'react-native-version'>;
}
declare module 'react-native-version/test/amend.js' {
  declare module.exports: $Exports<'react-native-version/test/amend'>;
}
declare module 'react-native-version/test/amend.skipTag.js' {
  declare module.exports: $Exports<'react-native-version/test/amend.skipTag'>;
}
declare module 'react-native-version/test/default.js' {
  declare module.exports: $Exports<'react-native-version/test/default'>;
}
declare module 'react-native-version/test/default.skipTag.js' {
  declare module.exports: $Exports<'react-native-version/test/default.skipTag'>;
}
declare module 'react-native-version/test/fixtures/index.js' {
  declare module.exports: $Exports<'react-native-version/test/fixtures/index'>;
}
declare module 'react-native-version/test/helpers/apiMacro.js' {
  declare module.exports: $Exports<'react-native-version/test/helpers/apiMacro'>;
}
declare module 'react-native-version/test/helpers/beforeEach.js' {
  declare module.exports: $Exports<'react-native-version/test/helpers/beforeEach'>;
}
declare module 'react-native-version/test/helpers/cliMacro.js' {
  declare module.exports: $Exports<'react-native-version/test/helpers/cliMacro'>;
}
declare module 'react-native-version/test/helpers/execAsync.js' {
  declare module.exports: $Exports<'react-native-version/test/helpers/execAsync'>;
}
declare module 'react-native-version/test/helpers/getCurrCommitHash.js' {
  declare module.exports: $Exports<'react-native-version/test/helpers/getCurrCommitHash'>;
}
declare module 'react-native-version/test/helpers/getCurrTagHash.js' {
  declare module.exports: $Exports<'react-native-version/test/helpers/getCurrTagHash'>;
}
declare module 'react-native-version/test/helpers/getCurrTree.js' {
  declare module.exports: $Exports<'react-native-version/test/helpers/getCurrTree'>;
}
declare module 'react-native-version/test/helpers/getCurrVersion.js' {
  declare module.exports: $Exports<'react-native-version/test/helpers/getCurrVersion'>;
}
declare module 'react-native-version/test/helpers/gitPathnames.js' {
  declare module.exports: $Exports<'react-native-version/test/helpers/gitPathnames'>;
}
declare module 'react-native-version/test/helpers/npmScriptsMacro.js' {
  declare module.exports: $Exports<'react-native-version/test/helpers/npmScriptsMacro'>;
}
declare module 'react-native-version/test/helpers/tempInitAndVersion.js' {
  declare module.exports: $Exports<'react-native-version/test/helpers/tempInitAndVersion'>;
}
declare module 'react-native-version/test/incrementBuild.js' {
  declare module.exports: $Exports<'react-native-version/test/incrementBuild'>;
}
declare module 'react-native-version/test/neverAmend.js' {
  declare module.exports: $Exports<'react-native-version/test/neverAmend'>;
}
declare module 'react-native-version/test/resetBuild.js' {
  declare module.exports: $Exports<'react-native-version/test/resetBuild'>;
}
declare module 'react-native-version/util.js' {
  declare module.exports: $Exports<'react-native-version/util'>;
}
