// flow-typed signature: b68ac13ea67e6cfa8492883d979760d1
// flow-typed version: <<STUB>>/react-native-pages_v^0.6.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-pages'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-pages' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-pages/src/components/indicator/index' {
  declare module.exports: any;
}

declare module 'react-native-pages/src/components/indicator/styles' {
  declare module.exports: any;
}

declare module 'react-native-pages/src/components/pages/index' {
  declare module.exports: any;
}

declare module 'react-native-pages/src/components/pages/styles' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-pages/index' {
  declare module.exports: $Exports<'react-native-pages'>;
}
declare module 'react-native-pages/index.js' {
  declare module.exports: $Exports<'react-native-pages'>;
}
declare module 'react-native-pages/src/components/indicator/index.js' {
  declare module.exports: $Exports<'react-native-pages/src/components/indicator/index'>;
}
declare module 'react-native-pages/src/components/indicator/styles.js' {
  declare module.exports: $Exports<'react-native-pages/src/components/indicator/styles'>;
}
declare module 'react-native-pages/src/components/pages/index.js' {
  declare module.exports: $Exports<'react-native-pages/src/components/pages/index'>;
}
declare module 'react-native-pages/src/components/pages/styles.js' {
  declare module.exports: $Exports<'react-native-pages/src/components/pages/styles'>;
}
