// flow-typed signature: 418c8844652c158b7349f6b2de69184b
// flow-typed version: <<STUB>>/react-native-svg-image_v^2.0.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-svg-image'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-svg-image' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-svg-image/index' {
  declare module.exports: $Exports<'react-native-svg-image'>;
}
declare module 'react-native-svg-image/index.js' {
  declare module.exports: $Exports<'react-native-svg-image'>;
}
