// flow-typed signature: cf538e07a61a48750771cae1aba2b316
// flow-typed version: <<STUB>>/react-composer_v^5.0.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-composer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-composer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-composer/dist/react-composer' {
  declare module.exports: any;
}

declare module 'react-composer/dist/react-composer.min' {
  declare module.exports: any;
}

declare module 'react-composer/es/index' {
  declare module.exports: any;
}

declare module 'react-composer/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-composer/dist/react-composer.js' {
  declare module.exports: $Exports<'react-composer/dist/react-composer'>;
}
declare module 'react-composer/dist/react-composer.min.js' {
  declare module.exports: $Exports<'react-composer/dist/react-composer.min'>;
}
declare module 'react-composer/es/index.js' {
  declare module.exports: $Exports<'react-composer/es/index'>;
}
declare module 'react-composer/lib/index.js' {
  declare module.exports: $Exports<'react-composer/lib/index'>;
}
