// flow-typed signature: f898262498f8475afd24dfc8857159e6
// flow-typed version: <<STUB>>/react-native-select-input-ios_v^1.1.4/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-select-input-ios'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-select-input-ios' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-select-input-ios/src/components/CustomKeyboard' {
  declare module.exports: any;
}

declare module 'react-native-select-input-ios/src/components/KeyboardButton' {
  declare module.exports: any;
}

declare module 'react-native-select-input-ios/src/components/PickerKeyboard' {
  declare module.exports: any;
}

declare module 'react-native-select-input-ios/src/components/selectinput/AbstractSelectInput' {
  declare module.exports: any;
}

declare module 'react-native-select-input-ios/src/components/selectinput/SelectInput.android' {
  declare module.exports: any;
}

declare module 'react-native-select-input-ios/src/components/selectinput/SelectInput.ios' {
  declare module.exports: any;
}

declare module 'react-native-select-input-ios/src/index' {
  declare module.exports: any;
}

declare module 'react-native-select-input-ios/src/stylesheets/customKeyboard.css' {
  declare module.exports: any;
}

declare module 'react-native-select-input-ios/src/stylesheets/pickerKeyboard.css' {
  declare module.exports: any;
}

declare module 'react-native-select-input-ios/src/stylesheets/selectInputAndroid.css' {
  declare module.exports: any;
}

declare module 'react-native-select-input-ios/src/stylesheets/selectInputIOS.css' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-select-input-ios/src/components/CustomKeyboard.js' {
  declare module.exports: $Exports<'react-native-select-input-ios/src/components/CustomKeyboard'>;
}
declare module 'react-native-select-input-ios/src/components/KeyboardButton.js' {
  declare module.exports: $Exports<'react-native-select-input-ios/src/components/KeyboardButton'>;
}
declare module 'react-native-select-input-ios/src/components/PickerKeyboard.js' {
  declare module.exports: $Exports<'react-native-select-input-ios/src/components/PickerKeyboard'>;
}
declare module 'react-native-select-input-ios/src/components/selectinput/AbstractSelectInput.js' {
  declare module.exports: $Exports<'react-native-select-input-ios/src/components/selectinput/AbstractSelectInput'>;
}
declare module 'react-native-select-input-ios/src/components/selectinput/SelectInput.android.js' {
  declare module.exports: $Exports<'react-native-select-input-ios/src/components/selectinput/SelectInput.android'>;
}
declare module 'react-native-select-input-ios/src/components/selectinput/SelectInput.ios.js' {
  declare module.exports: $Exports<'react-native-select-input-ios/src/components/selectinput/SelectInput.ios'>;
}
declare module 'react-native-select-input-ios/src/index.js' {
  declare module.exports: $Exports<'react-native-select-input-ios/src/index'>;
}
declare module 'react-native-select-input-ios/src/stylesheets/customKeyboard.css.js' {
  declare module.exports: $Exports<'react-native-select-input-ios/src/stylesheets/customKeyboard.css'>;
}
declare module 'react-native-select-input-ios/src/stylesheets/pickerKeyboard.css.js' {
  declare module.exports: $Exports<'react-native-select-input-ios/src/stylesheets/pickerKeyboard.css'>;
}
declare module 'react-native-select-input-ios/src/stylesheets/selectInputAndroid.css.js' {
  declare module.exports: $Exports<'react-native-select-input-ios/src/stylesheets/selectInputAndroid.css'>;
}
declare module 'react-native-select-input-ios/src/stylesheets/selectInputIOS.css.js' {
  declare module.exports: $Exports<'react-native-select-input-ios/src/stylesheets/selectInputIOS.css'>;
}
