// flow-typed signature: 5f436b9bffb0ebfd5e7d796856309714
// flow-typed version: <<STUB>>/react-native-markdown-syntax_v^0.1.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-markdown-syntax'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-markdown-syntax' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-markdown-syntax/lib/index' {
  declare module.exports: any;
}

declare module 'react-native-markdown-syntax/lib/md' {
  declare module.exports: any;
}

declare module 'react-native-markdown-syntax/lib/react_helpers' {
  declare module.exports: any;
}

declare module 'react-native-markdown-syntax/Markdown' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-markdown-syntax/lib/index.js' {
  declare module.exports: $Exports<'react-native-markdown-syntax/lib/index'>;
}
declare module 'react-native-markdown-syntax/lib/md.js' {
  declare module.exports: $Exports<'react-native-markdown-syntax/lib/md'>;
}
declare module 'react-native-markdown-syntax/lib/react_helpers.js' {
  declare module.exports: $Exports<'react-native-markdown-syntax/lib/react_helpers'>;
}
declare module 'react-native-markdown-syntax/Markdown.js' {
  declare module.exports: $Exports<'react-native-markdown-syntax/Markdown'>;
}
