// flow-typed signature: 5b40ef6a2e3b4bb734bb3b426d67859b
// flow-typed version: <<STUB>>/redux-storage_v^4.1.2/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-storage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-storage' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-storage/build-es/actions' {
  declare module.exports: any;
}

declare module 'redux-storage/build-es/constants' {
  declare module.exports: any;
}

declare module 'redux-storage/build-es/createLoader' {
  declare module.exports: any;
}

declare module 'redux-storage/build-es/createMiddleware' {
  declare module.exports: any;
}

declare module 'redux-storage/build-es/index' {
  declare module.exports: any;
}

declare module 'redux-storage/build-es/reducer' {
  declare module.exports: any;
}

declare module 'redux-storage/build/actions' {
  declare module.exports: any;
}

declare module 'redux-storage/build/constants' {
  declare module.exports: any;
}

declare module 'redux-storage/build/createLoader' {
  declare module.exports: any;
}

declare module 'redux-storage/build/createMiddleware' {
  declare module.exports: any;
}

declare module 'redux-storage/build/index' {
  declare module.exports: any;
}

declare module 'redux-storage/build/reducer' {
  declare module.exports: any;
}

declare module 'redux-storage/src/actions' {
  declare module.exports: any;
}

declare module 'redux-storage/src/constants' {
  declare module.exports: any;
}

declare module 'redux-storage/src/createLoader' {
  declare module.exports: any;
}

declare module 'redux-storage/src/createMiddleware' {
  declare module.exports: any;
}

declare module 'redux-storage/src/index' {
  declare module.exports: any;
}

declare module 'redux-storage/src/reducer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-storage/build-es/actions.js' {
  declare module.exports: $Exports<'redux-storage/build-es/actions'>;
}
declare module 'redux-storage/build-es/constants.js' {
  declare module.exports: $Exports<'redux-storage/build-es/constants'>;
}
declare module 'redux-storage/build-es/createLoader.js' {
  declare module.exports: $Exports<'redux-storage/build-es/createLoader'>;
}
declare module 'redux-storage/build-es/createMiddleware.js' {
  declare module.exports: $Exports<'redux-storage/build-es/createMiddleware'>;
}
declare module 'redux-storage/build-es/index.js' {
  declare module.exports: $Exports<'redux-storage/build-es/index'>;
}
declare module 'redux-storage/build-es/reducer.js' {
  declare module.exports: $Exports<'redux-storage/build-es/reducer'>;
}
declare module 'redux-storage/build/actions.js' {
  declare module.exports: $Exports<'redux-storage/build/actions'>;
}
declare module 'redux-storage/build/constants.js' {
  declare module.exports: $Exports<'redux-storage/build/constants'>;
}
declare module 'redux-storage/build/createLoader.js' {
  declare module.exports: $Exports<'redux-storage/build/createLoader'>;
}
declare module 'redux-storage/build/createMiddleware.js' {
  declare module.exports: $Exports<'redux-storage/build/createMiddleware'>;
}
declare module 'redux-storage/build/index.js' {
  declare module.exports: $Exports<'redux-storage/build/index'>;
}
declare module 'redux-storage/build/reducer.js' {
  declare module.exports: $Exports<'redux-storage/build/reducer'>;
}
declare module 'redux-storage/src/actions.js' {
  declare module.exports: $Exports<'redux-storage/src/actions'>;
}
declare module 'redux-storage/src/constants.js' {
  declare module.exports: $Exports<'redux-storage/src/constants'>;
}
declare module 'redux-storage/src/createLoader.js' {
  declare module.exports: $Exports<'redux-storage/src/createLoader'>;
}
declare module 'redux-storage/src/createMiddleware.js' {
  declare module.exports: $Exports<'redux-storage/src/createMiddleware'>;
}
declare module 'redux-storage/src/index.js' {
  declare module.exports: $Exports<'redux-storage/src/index'>;
}
declare module 'redux-storage/src/reducer.js' {
  declare module.exports: $Exports<'redux-storage/src/reducer'>;
}
