// flow-typed signature: c1b93e978ed765ca4ea6719679b2c45d
// flow-typed version: <<STUB>>/redux-enhancer-react-native-appstate_v^0.3.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-enhancer-react-native-appstate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-enhancer-react-native-appstate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'redux-enhancer-react-native-appstate/index' {
  declare module.exports: $Exports<'redux-enhancer-react-native-appstate'>;
}
declare module 'redux-enhancer-react-native-appstate/index.js' {
  declare module.exports: $Exports<'redux-enhancer-react-native-appstate'>;
}
