// flow-typed signature: c45ca725d7d33a5f2e4460e44cea5a36
// flow-typed version: <<STUB>>/simple-markdown_v^0.3.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'simple-markdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'simple-markdown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'simple-markdown/__tests__/simple-markdown-test' {
  declare module.exports: any;
}

declare module 'simple-markdown/simple-markdown' {
  declare module.exports: any;
}

declare module 'simple-markdown/simple-markdown.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'simple-markdown/__tests__/simple-markdown-test.js' {
  declare module.exports: $Exports<'simple-markdown/__tests__/simple-markdown-test'>;
}
declare module 'simple-markdown/index' {
  declare module.exports: $Exports<'simple-markdown'>;
}
declare module 'simple-markdown/index.js' {
  declare module.exports: $Exports<'simple-markdown'>;
}
declare module 'simple-markdown/simple-markdown.js' {
  declare module.exports: $Exports<'simple-markdown/simple-markdown'>;
}
declare module 'simple-markdown/simple-markdown.min.js' {
  declare module.exports: $Exports<'simple-markdown/simple-markdown.min'>;
}
