export const CHECKIN_PHYSICALLY    = 'CheckinPhysically'
export const CHECKIN_EMOTIONALLY   = 'CheckinEmotionally'
export const CHECKIN_MENTALLY      = 'CheckinMentally'
export const CHECKIN_DAILY         = 'CheckinDaily'
export const CHECKIN_MOOD         = 'CheckingMood'
export const CHECKIN_MEDITATION   = 'CheckingMeditation'
export const CHECKIN_EMOJI        = 'CheckingEmoji'
