export const lightblue = '#48d0f1';
export const seafoamBlue = '#6AC2ED'; //(MEDITATION PGase)
export const white = 'white';
export const deepBlue = '#00098A';
export const whiteTwo = '#fcfcfc';
export const lightGrey = '#fefefe';
export const white90 = 'rgba(255, 255, 255, 0.9)';
export const duskBlue = '#262d85';
export const hotPink = '#EB008B';
export const facebookColor = '#3b5998';
