import {
    CHECKIN_PHYSICALLY,
    CHECKIN_EMOTIONALLY,
    CHECKIN_MENTALLY,
    CHECKIN_DAILY,
    CHECKIN_MOOD,
    CHECKIN_MEDITATION,
    CHECKIN_EMOJI,
} from './checkins'

export const APP_INSTURUCTION_NOTIFICATION      = 'AppInsturuction'
export const NEXT_STEP_SUGGESTIONS_NOTIFICATION = 'NextStepSuggestions'
export const RESUME_WORK_ON_FORM_NOTIFICATION   = 'ResumeWorkOnForm'
export const READ_MORE_ABOUT_STEP_NOTIFICATION  = 'ReadMoreAboutStep'
export const CHECKIN_PHYSICALLY_NOTIFICATION    =  CHECKIN_PHYSICALLY
export const CHECKIN_EMOTIONALLY_NOTIFICATION   =  CHECKIN_EMOTIONALLY
export const CHECKIN_MENTALLY_NOTIFICATION      =  CHECKIN_MENTALLY
export const CHECKIN_DAILY_NOTIFICATION         =  CHECKIN_DAILY
export const CHECKIN_MOOD_NOTIFICATION          =  CHECKIN_MOOD
export const CHECKIN_MEDITATION_NOTIFICATION    =  CHECKIN_MEDITATION
export const CHECKIN_EMOJI_NOTIFICATION         =  CHECKIN_EMOJI
