export const SUGGESION_NAME_FIELD        = 'name'
export const NEXT_STEP_SUGGESTION_NAME   = 'NextStepSuggstion'
export const MEDITATIONS_SUGGESTION_NAME = 'MeditationSuggstion'

export const REFLECTION                  = 'REFLECTION'
export const TEAMWORK                    = 'TEAMWORK'
export const GOALS                       = 'GOALS'
export const CAREER                      = 'CAREER'
export const HOBBIES                     = 'HOBBIES'
export const HEALTH                      = 'HEALTH'
export const RELATIONSHIPS               = 'RELATIONSHIPS'
export const ENVIRONMENT                 = 'ENVIRONMENT'
export const SPIRITUALITY                = 'SPIRITUALITY'
export const PHASE1                      = 'PHASE1'
export const PHASE2                      = 'PHASE2'
export const PHASE3                      = 'PHASE3'
export const NEIGHBOR                    = 'NEIGHBOR'

export const SUGGESTION                  = 'SUGGESTION'
export const CHECKIN                     = 'CHECKIN'