# Uncomment the next line to define a global platform for your project
  platform :ios, '9.0'

target 'Lifevision' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for Lifevision
  # Required by RNFirebase
  pod 'Firebase/Core', '~> 6.3.0'


  

  target 'LifevisionTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Lifevision-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for Lifevision-tvOS

  target 'Lifevision-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
