const nextStepMotivation = {
  '1': `Welcome to the 20/20 Life Vision Challenge! We suggest starting with Step 1: The Rocking Chair.`,
  '2': `Congratulations, you have completed The Rocking Chair! Now you can begin Step 2, where we’ll help you optimize your ideal 168 hour week.`,
  '3': `Nice work - you have completed Step 2. Let’s move on to Step 3, where you will engage in constructive self-reflection regarding your strengths and weaknesses and how they have helped or hindered in pursuit of your goals.`,
  '4': `Good job, you have completed What are my strengths and weaknesses? In step 4 - you will form your Board of Advisors for the Life Vision Challenge. A strong community is foundational for becoming the best possible you.`,
  '5': `Your Board of Advisors is formed! Their support and communication will aid your journey going forward. The next step is to begin setting and classifying your life goals according to the seven goal types.`,
  '6': `Now that you’ve clearly set goals for yourself, you can begin step 6, where you will meditate on the goals of people in your inner circle, and how you can best support them. In the 20/20 Life Vision Challenge, giving is just as important as receiving.`,
  '7': `Setting goals? Piece of cake. Following through? For many of us, this is the hard part. Step 7 will help you analyze what happens after you set your goals, which will be very helpful for achieving them.`,
  '8': `You’ve completed step 7 - let’s move on to step 8 - What is my Internal Energy Level? Here, you’ll meditate on how you’re feeling at different times and in different situations. This will help you gain perspective on where you’re doing great and where you can look to improve.`,
  '9': `Nice work, you’ve completed step 8. Go ahead and jump into step 9, where you will meditate on who your role models are, and when and how they have influenced you in various areas of your life.`,
  '10': `You’re doing great - you’re almost done with phase 1 of the 20/20 Life Vision Challenge. It’s time to complete step 10, where you will look within, meditate on the various parts of your internal world, and determine how they have helped or hindered you in your journey thus far.`,
  '11': `Congratulations! You’ve completed Phase 1: Meditation. Now, we move on to Phase 2: Assessment. Let’s begin with step 11, where you will assess your goals over the last 5 years.`,
  '12': `Now you’re ready to start step 12: Major Life Events. Picking up where you left off in step 11, you’ll analyze the MLEs of your past 5 years, and what kind of effects they had.`,
  '13': `Step 12 complete. You’re doing great. in Step 13, you will be begin the process of self-assessment for each of the 7 Pillars of Life. This step focuses on career.`,
  '14': `Congratulations, step 13 is complete. Self assessment is very important in the 20/20 Life Vision Challenge. We know it’s not easy! You’re doing great. The next assessment is Step 14, which focuses on finances.`,
  '15': `Great, you’ve completed step 14! Work/life balance is a fundamental piece of the Timebug philosophy. Now that you’ve assessed career and finances, the next assessment in Step 15 focuses on personal aims and hobbies.`,
  '16': `Step 15 complete! Awesome! Step 16’s assessment focuses on health and well-being. At Timebug, health is a holistic concept, so we’ll ask you to examine it from the physical, psychological and spiritual perspective.`,
  '17': `Good job, your health and well-being assessment is complete. Four down, three to go! In Step 18, you will turn your focus to the inter-personal and assess all of the relationships in your life.`,
  '18': `Nice work, step 17 is complete. In Step 18, you’ll move your gaze from within, look around yourself and assess your current environment.`,
  '19': `Great work - your assessment of the 7 Pillars of Life is almost complete! Our last assessment focuses on spirituality and it's role in your life.`,
  '20': `You’ve almost completed the 2nd phase of the 20/20 Life Vision Challenge! In step 20, you’ll look back and reflect on your assessments of the last 5 years. We’ll use that as a spring board to the final phase, Vision Creation.`,
  '21': `Congratulations - with the completion of Step 20, you are ready for Vision Creation, the 3rd and final phase of the 20/20 Life Vision Challenge. Let’s begin with Step 21, where you will visualize planting seeds in your Life Garden to begin manifesting your goals.`,
  '22': `Great, step 21 is complete. Our (literal) dreams are one of the greatest revealers of our sub conscious -  among other things. With this in mind, let’s jump into step 22, where you’ll write down and analyze your dreams.`,
  '23': `Good job completing step 22. In phase 2 you did a self assessment for all 7 Pillars of Life. Similarly, in phase 3 you will do an exercise in Vision Creation for all 7 pillars. Step 23 focuses on career.`,
  '24': `you finished step 23! Finances and Career are different pillars, but the two are closely related. With that in mind, let’s jump into step 24 and begin the process of Vision Creation for your finances.`,
  '25': `You finished step 24! In step 25, we’ll continue our process of Vision Creation, this time focusing on Aims & Hobbies.`,
  '26': `25 Steps complete! You’re close to finish line! In step 26, you will focus on Vision Creation for your Health and Wellness.`,
  '27': `Great job, step 26 is complete. It’s time to move onto the next phase on your Vision Creation. In step 27, we’ll focus on relationships.`,
  '28': `Nice, you’ve completed step 27! Don’t stop now, that challenge is almost complete! In step 28, you’ll continue the process of Vision Creation with a focus on your Environment.`,
  '29': `Good job - you’ve completed step 28! You’ve arrive at the final stage of your Vision Creation - step 29, where you will focus on the final Pillar of Life, Spirituality.`,
  '30': `Congratulations!! You’ve arrived at the final step of the 20/20 Life Vision Challenge! The last thing you’ll need to do is map out the next year of your life based on all the work you’ve done thus far. This will be a powerful reference and motivational tool going forward. Good luck and remember - this is not an end, but the beginning of the real work - the fun part!`
}

export default nextStepMotivation